### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [sowjanyaduvvuri/prj-rev-bwfs-dasmoto#4]
Grade: Exceeds expectations

Summary: Really nice job on this project, the site looks good. You used a lot of good techniques and kept your code well organized. Your CSS looks very efficient as well. Take a look at the issues I created for some best practice tips and new techniques you can start using. Overall really well done, you are ready for the next units.

**Comment by sowjanyaduvvuri** [comment]
Thank you Thank you so much for the positive review! :) I will look into the issues provided and be careful to not repeat them. Thank you once again!!!
